services:
  tag-box-nginx:
    build:
      context: docker/nginx
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - tag-box-php-fpm
      - tag-box-db
    networks:
      - tag-box-network
    restart: always # Automatically restart the container if it stops

  tag-box-php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - .:/app
    networks:
      - tag-box-network
    restart: always # Automatically restart the container

  tag-box-php-cli:
    build:
      context: docker/php-cli
    volumes:
      - .:/app
    networks:
      - tag-box-network
    environment:
      PHP_CS_FIXER_IGNORE_ENV: true

  tag-box-db:
      image: postgres:15.4
      restart: always
      environment:
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        POSTGRES_DB: tag-box
      volumes:
        - pg_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - tag-box-network

networks:
  tag-box-network:
    driver: bridge

volumes:
  pg_data:
